FROM redislabs/redisearch:latest
# # 下载并编译RedisSearch模块
# RUN apt-get update && apt-get install -y --no-install-recommends
# RUN apt-get install -y build-essential
# RUN apt-get install -y libhiredis-dev
# RUN apt-get install -y curl
# RUN rm -rf /var/lib/apt/lists/*